### ISSUE TITLE
Never loads in Safari

### ISSUE THREAD

**Issue by ZaneH** [tholman/the-pattern-library#5]
When attempting to load the page in Safari, I get 2 unique errors.

![screen shot 2016-01-09 at 2 55 57 am](https://cloud.githubusercontent.com/assets/8400251/12215123/c2dfeeae-b67c-11e5-8b60-b394a443a85a.png)

The latter error only happens when the window is resized.

**Comment by caleyshemc** [comment]
+1 Seeing the same error in Chrome and Firefox.

**Comment by pagrawl3** [comment]
+1

**Comment by tholman** [comment]
Fixed
